FROM jrei/systemd-debian:9

RUN sed -i 's|http://deb.debian.org|http://archive.debian.org|g' /etc/apt/sources.list && \
    sed -i 's|http://security.debian.org|http://archive.debian.org|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
